# Generated by Django 5.0.7 on 2024-07-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_permissions_alter_user_groups_alter_user_roles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('can_view_document', 'Can view document'), ('can_edit_document', 'Can edit document'), ('can_archivate_document', 'can archivate_document'), ('can_generate_rapport', 'can_generate_rapport')]},
        ),
    ]
