# Generated by Django 4.2 on 2024-12-10 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_service_transfertdocument_typedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to=settings.AUTH_USER_MODEL),
        ),
    ]
