# Generated by Django 4.2 on 2024-12-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_folder_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to='accounts.customuser'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_documents', to='accounts.customuser'),
        ),
    ]
