# Generated by Django 4.2 on 2024-12-12 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_transfertdocument_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertdocument',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_documents', to='accounts.document'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
