# Generated by Django 4.2 on 2024-12-12 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_alter_transfertdocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertdocument',
            name='decryption_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Code de déchiffrement'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_documents', to='accounts.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_documents', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='type_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.typedocument', verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi"),
        ),
    ]
