# Generated by Django 4.2 on 2024-12-19 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_remove_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfertdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='transfertdocument',
            name='service',
        ),
        migrations.RemoveField(
            model_name='transfertdocument',
            name='type_document',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.typedocument'),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.folder'),
        ),
        migrations.AlterField(
            model_name='document',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.service'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
