# Generated by Django 4.2 on 2024-12-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_transfertdocument_file_and_more'),
    ]

    operations = [
    ]
