# Generated by Django 4.2 on 2024-12-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20241219_1840'),
    ]

    operations = [
    ]
