# Generated by Django 4.2 on 2024-12-19 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_alter_document_document_type_alter_document_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertdocument',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transfert', to='accounts.document'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
