# Generated by Django 4.2 on 2024-12-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_transfertdocument_file_and_more'),
    ]

    operations = [
    ]
