# Generated by Django 4.2 on 2024-12-19 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0022_auto_20241219_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfertdocument',
            options={'permissions': [('can_view_document', 'Can view document'), ('can_edit_document', 'Can edit document')]},
        ),
        migrations.AddField(
            model_name='transfertdocument',
            name='droit_access',
            field=models.ManyToManyField(to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='transfertdocument',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='accounts.document'),
        ),
    ]
