# Generated by Django 4.2 on 2024-12-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_transfertdocument_droit_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
