# Generated by Django 4.2 on 2024-12-19 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_transfertdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertdocument',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='accounts.document'),
        ),
    ]
