# Generated by Django 4.2 on 2024-12-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_transfertdocument_file'),
    ]

    operations = [
    ]
