# Generated by Django 4.2 on 2024-12-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20241219_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_type',
            new_name='type',
        ),
    ]
