# Generated by Django 4.2 on 2024-12-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_document_type_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertdocument',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='accounts.document', verbose_name='Document'),
        ),
    ]
