# Generated by Django 4.2 on 2024-12-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_transfertdocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfertdocument',
            name='file',
        ),
        migrations.AddField(
            model_name='transfertdocument',
            name='files',
            field=models.ManyToManyField(related_name='transfers', to='accounts.document', verbose_name='Documents'),
        ),
    ]
