# Generated by Django 4.2 on 2024-12-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_transfertdocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
