"""
Django settings for GED project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see:
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Base Directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Security Settings
SECRET_KEY = 'django-insecure-ofy)q-8rd62(qoa*%e^xb6%uc8^!izs_ca6#8m5%6t@hfhe#2e'
DEBUG = True
ALLOWED_HOSTS = []

# URLs for Login and Logout
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'  # Redirect after login
LOGOUT_REDIRECT_URL = '/'  # Redirect after logout

# Static & Media Files
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Installed Applications
INSTALLED_APPS = [
    'jazzmin',  # Jazzmin for Admin Panel
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',  # Your application
    'rest_framework',  # Django REST Framework
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.ProtectedMediaMiddleware',
]

# URL Configuration
ROOT_URLCONF = 'GED.urls'

# Templates Configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI Application
WSGI_APPLICATION = 'GED.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password Validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Default Primary Key Field Type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your_email_password'

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_header": "Tableau de Bord UNA",
    "site_title": "Gestion UNA",
    "site_brand": "UNA Archive",
    "site_logo": "images/logo.png",  # Replace with your logo path
    "welcome_sign": "Page de connexion",
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {  
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts.Role": "fas fa-user-shield",
        "accounts.Folder": "fas fa-folder",
        "accounts.Document": "fas fa-file",
        "accounts.Service": "fas fa-cogs",
        "accounts.TypeDocument": "fas fa-tags",
        "accounts.TransfertDocument": "fas fa-exchange-alt",
    },
    "custom_css": "css/style.css",  # Custom CSS
    "custom_js": "js/script.js",  # Custom JavaScript
    "topmenu_links": [ 
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"app": "accounts"}, 
    ],
    "footer_text": "UNA Archive - Tous droits réservés",
    "order_with_respect_to": ["auth", "accounts"],
    "external_css": [
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    ],
}
